from django.urls import path
from . import views

urlpatterns = [
    path('notes/',
         views.notes_plug, name='note-list-view'),
    path('<int:pk>/',
         views.UserDetailView.as_view(), name='user-detail-view'),
    path('<int:pk>/create_team/',
         views.TeamCreateView.as_view(), name='team-create-view'),
    path('<int:pk>/teams/',
         views.UserTeamsDetailView.as_view(), name='userteams-detail-view'),
    path('<int:pk>/own_teams/',
         views.OwnTeamsListView.as_view(), name='ownteams-list-view'),
    path('<uuid:team_id>/',
         views.TeamNotesListView.as_view(), name='teamnotes-list-view'),
    path('<uuid:team_id>/archived_notes',
         views.TeamArchivedNotesListView.as_view(), name='archivednotes-list-view'),
    path('<uuid:team_id>/add_note/',
         views.TeamNoteCreateView.as_view(), name='teamnote-create-view'),
    path('<uuid:team_id>/delete_team/',
         views.TeamDeleteView.as_view(), name='team-delete-view'),
    path('<uuid:team_id>/add_member/',
         views.TeamAddMemberUpdateView.as_view(), name='addmember-update-view'),
    path('<uuid:team_id>/members/',
         views.TeamMembersDetailView.as_view(), name='members-detail-view'),
    path('<uuid:team_id>/delete_member/',
         views.delete_member, name='delete-member'),
    path('<uuid:team_id>/<uuid:pk>/',
         views.NoteDetailView.as_view(), name='note-detail-view'),
    path('<uuid:team_id>/<uuid:pk>/archive/',
         views.archive_note, name='archive-note'),
    path('<uuid:team_id>/<uuid:pk>/update/',
         views.TeamNoteUpdateView.as_view(), name='note-update-view'),
    path('<uuid:team_id>/<uuid:pk>/delete/',
         views.NoteDeleteView.as_view(), name='note-delete-view'),
]
